name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  Build:
    env:
      WIN_VER_LATEST: ltsc2022
    strategy:
      fail-fast: false
      matrix:
        WIN_VER:
        - ltsc2022
        - ltsc2025
        - ltsc2019
        - ltsc2016
        VS_VER:
        - 2022
        - 2019
        - 2017
        WORKLOAD:
        - vctools
        - xamarinbuildtools
        - nodebuildtools
        - officebuildtools
        - universalbuildtools
        - webbuildtools
        - netcorebuildtools
        - manageddesktopbuildtools
        - azurebuildtools
        - databuildtools

    runs-on: windows-2025
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Pull and tag parent image
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}buildtools:${{ matrix.WIN_VER }}
        docker tag  ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}buildtools:${{ matrix.WIN_VER }} ${{ secrets.DOCKERHUB_USERNAME }}/visualstudio${{ matrix.VS_VER }}buildtools:${{ matrix.WIN_VER }}
    - name: Build
      run: >
        docker build
        --build-arg WIN_VER=${{ matrix.WIN_VER }}
        --build-arg VS_VER=${{ matrix.VS_VER }}
        --build-arg WORKLOAD=${{ matrix.WORKLOAD }}
        --tag=${{ secrets.DOCKERHUB_USERNAME }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}:${{ matrix.WIN_VER }}
        --tag=ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}:${{ matrix.WIN_VER }}
        --isolation=hyperv
        .
    - name: Tag latest
      if: ${{ matrix.WIN_VER == env.WIN_VER_LATEST }}
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}:${{ matrix.WIN_VER }} ${{ secrets.DOCKERHUB_USERNAME }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}
        docker tag ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}:${{ matrix.WIN_VER }} ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }}

    - name: push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }} --all-tags
        docker push ghcr.io/${{ github.repository_owner }}/visualstudio${{ matrix.VS_VER }}-workload-${{ matrix.WORKLOAD }} --all-tags
